### ISSUE TITLE
Wynntils' Jenkins is decommisioned

### ISSUE THREAD

**Issue by HighCrit** [Vidanox/WynncraftEnhanced#3]
> Wynntils for 1.18 has not yet officialy released, as it is still being worked on. You'll have to download the fabric .jar from here https://ci.wynntils.com/job/Artemis/lastSuccessfulBuild/ and put it in your mods folder.

The Artemis build can now be obtained from https://modrinth.com/mod/wynntils

**Comment by Vidanox** [comment]
thank you, will update it when I get home

**Comment by Vidanox** [comment]
resolved in 0.4

**Comment by Vidanox** [comment]
resolved in 0.4
